on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@main
      - name: checkout repo
        uses: actions/checkout@main
      - name: save secret to file
        run: |
          echo $MKOSI_KEY > mkosi.key
          echo $MKOSI_CRT > mkosi.crt
          chmod 600 mkosi.key
          ls -la mkosi.key mkosi.crt
          sha256sum mkosi.crt
          sha256sum mkosi.key
          pwd
        env:
          MKOSI_KEY: ${{ secrets.MKOSI_KEY }}
          MKOSI_CRT: ${{ secrets.MKOSI_CRT }}

      - name: version
        run: |
          mkosi --version
      - name: summary
        run: |
          mkosi summary --no-pager
      - name: build
        run: |
          mkosi build --compress-output=yes --debug

      - name: list artifacts
        run: |
          ls -la mkosi.output
